# Generated by Django 2.0.7 on 2018-07-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
