# Generated by Django 2.0.7 on 2018-07-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penpals', '0002_auto_20180709_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='user',
        ),
        migrations.AlterField(
            model_name='penpal',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penpals.Address'),
        ),
    ]
